### ISSUE TITLE
Adding Ticket No.

### ISSUE THREAD

**Issue by jayo2005** [techblue/vtiger-libreoffice-mailmerge#9]
I am trying to add Ticket title and Ticket number for printing labels. Ticket title works but Ticket number does not. Here is my template.

TICKET_TITLE
TICKET_NO

Vtiger Version = 6.1
PHP version =  5.3.29

**Comment by gurvinderdadyala** [comment]
@jayo2005 TICKET_NO field does not exist in table. Correct field name is TICKET_TICKETNO. 
You can always go "Module Merge Field List " section to check correct field names used for specific modules. 
To access  "Module Merge Field List " click on Mail Merge and on right hand side you will find "Module Merge Field List " button
